name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ls -a
      - name: checkout the master branch
        uses: actions/checkout@v1
        with:
          ref: master
          # script: ls -a
      - run: ls -a
      - run: /bin/bash deploy.sh
