name: Remote SSH Deployment
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh command via HOST IP, HOST USERNAME and SSH PRIVATE KEY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            curl -X GET https://api.ipify.org
            git clone https://${{ secrets.GH_TOKEN }}@github.com/manashmandal/workflow.git
            cd workflow
            /bin/bash deploy.sh